const bard = {
    'Resonant Greaves': 'Resonant Greaves',
    'Resonant Vambraces': 'Resonant Vambraces',
    'Resonant Breastplate': 'Resonant Breastplate',
    'Resonant Helm': 'Resonant Helm',
    'Resonant Bracer': 'Resonant Bracer',
    'Resonant Gauntlets': 'Resonant Gauntlets',
    'Resonant Boots': 'Resonant Boots',
    'Troubadour\'s Helm': 'Troubadour\'s Helm',
    'Troubadour\'s Breastplate': 'Troubadour\'s Breastplate',
    'Troubadour\'s Vambraces': 'Troubadour\'s Vambraces',
    'Troubadour\'s Bracer': 'Troubadour\'s Bracer',
    'Troubadour\'s Gauntlets': 'Troubadour\'s Gauntlets',
    'Troubadour\'s Greaves': 'Troubadour\'s Greaves',
    'Troubadour\'s Boots': 'Troubadour\'s Boots',
    'Helm of Twilight': 'Helm of Twilight',
    'Breastplate of Twilight': 'Breastplate of Twilight',
    'Vambraces of Twilight': 'Vambraces of Twilight',
    'Bracer of Twilight': 'Bracer of Twilight',
    'Gauntlets of Twilight': 'Gauntlets of Twilight',
    'Greaves of Twilight': 'Greaves of Twilight',
    'Boots of Twilight': 'Boots of Twilight',
    'Melodic Helm': 'Melodic Helm',
    'Melodic Breastplate': 'Melodic Breastplate',
    'Melodic Vambraces': 'Melodic Vambraces',
    'Melodic Bracer': 'Melodic Bracer',
    'Melodic Gauntlets': 'Melodic Gauntlets',
    'Melodic Greaves': 'Melodic Greaves',
    'Melodic Boots': 'Melodic Boots'
}

const cleric = {
    'Crown of Forbidden Rites': 'Crown of Forbidden Rites',
    'Breastplate of Forbidden Rites': 'Breastplate of Forbidden Rites',
    'Vambraces of Forbidden Rites': 'Vambraces of Forbidden Rites',
    'Bracers of Forbidden Rites': 'Bracers of Forbidden Rites',
    'Gauntlets of Forbidden Rites': 'Gauntlets of Forbidden Rites',
    'Greaves of Forbidden Rites': 'Greaves of Forbidden Rites',
    'Boots of Forbidden Rites': 'Boots of Forbidden Rites',
    "Templar's Crown": "Templar's Crown",
  "Templar's Chestplate": "Templar's Chestplate",
  "Templar's Vambraces": "Templar's Vambraces",
  "Templar's Bracer": "Templar's Bracer",
  "Templar's Gauntlets": "Templar's Gauntlets",
  "Templar's Leggings": "Templar's Leggings",
  "Templar's Boots": "Templar's Boots",
  "Akkirus' Crown of the Risen": "Akkirus' Crown of the Risen",
  "Akkirus' Chestplate of the Risen": "Akkirus' Chestplate of the Risen",
  "Akkirus' Vambraces of the Risen": "Akkirus' Vambraces of the Risen",
  "Akkirus' Bracelet of the Risen": "Akkirus' Bracelet of the Risen",
  "Akkirus' Gauntlets of the Risen": "Akkirus' Gauntlets of the Risen",
  "Akkirus' Greaves of the Risen": "Akkirus' Greaves of the Risen",
  "Akkirus' Boots of the Risen": "Akkirus' Boots of the Risen",
  "Crown of Stability": "Crown of Stability",
  "Chestplate of Stability": "Chestplate of Stability",
  "Vambraces of Stability": "Vambraces of Stability",
  "Bracer of Stability": "Bracer of Stability",
  "Gauntlets of Stability": "Gauntlets of Stability",
  "Greaves of Stability": "Greaves of Stability",
  "Boots of Stability": "Boots of Stability",
};

const druid = {
    "Rowyl's Circlet of Nature": "Rowyl's Circlet of Nature",
  "Rowyl's Chestguard of Nature": "Rowyl's Chestguard of Nature",
  "Rowyl's Vambraces of Nature": "Rowyl's Vambraces of Nature",
  "Rowyl's Bracer of Nature": "Rowyl's Bracer of Nature",
  "Rowyl's Gauntlets of Nature": "Rowyl's Gauntlets of Nature",
  "Rowyl's Greaves of Nature": "Rowyl's Greaves of Nature",
  "Rowyl's Boots of Nature": "Rowyl's Boots of Nature",
  "Woven Grass Headband": "Woven Grass Headband",
  "Woven Grass Chestguard": "Woven Grass Chestguard",
  "Woven Grass Vambraces": "Woven Grass Vambraces",
  "Woven Grass Bracelet": "Woven Grass Bracelet",
  "Woven Grass Gauntlets": "Woven Grass Gauntlets",
  "Woven Grass Greaves": "Woven Grass Greaves",
  "Woven Grass Boots": "Woven Grass Boots",
  "Nature Walker's Circlet": "Nature Walker's Circlet",
  "Nature Walker's Chestguard": "Nature Walker's Chestguard",
  "Nature Walker's Vambraces": "Nature Walker's Vambraces",
  "Nature Walker's Bracer": "Nature Walker's Bracer",
  "Nature Walker's Gauntlets": "Nature Walker's Gauntlets",
  "Nature Walker's Boots": "Nature Walker's Boots",
  "Crown of Harmony": "Crown of Harmony",
  "Hauberk of Harmony": "Hauberk of Harmony",
  "Vambraces of Harmony": "Vambraces of Harmony",
  "Wristguard of Harmony": "Wristguard of Harmony",
  "Gloves of Harmony": "Gloves of Harmony",
  "Greaves of Harmony": "Greaves of Harmony",
  "Sandals of Harmony": "Sandals of Harmony",
}

const enchanter = {
    "Insidious Gloves": "Insidious Gloves",
  "Insidious Halo": "Insidious Halo",
  "Insidious Manacle": "Insidious Manacle",
  "Insidious Pantaloons": "Insidious Pantaloons",
  "Insidious Robe": "Insidious Robe",
  "Insidious Sleeves": "Insidious Sleeves",
  "Insidious Slippers": "Insidious Slippers",
  "Illusionist's Headband": "Illusionist's Headband",
  "Illusionist's Robe": "Illusionist's Robe",
  "Illusionist's Sleeves": "Illusionist's Sleeves",
  "Illusionist's Wristguard": "Illusionist's Wristguard",
  "Illusionist's Gloves": "Illusionist's Gloves",
  "Illusionist's Pantaloons": "Illusionist's Pantaloons",
  "Illusionist's Slippers": "Illusionist's Slippers",
  "Beguiler's Crown": "Beguiler's Crown",
  "Beguiler's Robe": "Beguiler's Robe",
  "Beguiler's Sleeves": "Beguiler's Sleeves",
  "Beguiler's Wristguard": "Beguiler's Wristguard",
  "Beguiler's Gloves": "Beguiler's Gloves",
  "Beguiler's Trousers": "Beguiler's Trousers",
  "Beguiler's Slippers": "Beguiler's Slippers",
  "Dazzling Circlet": "Dazzling Circlet",
  "Dazzling Robe": "Dazzling Robe",
  "Dazzling Sleeves": "Dazzling Sleeves",
  "Dazzling Wristguard": "Dazzling Wristguard",
  "Dazzling Gloves": "Dazzling Gloves",
  "Dazzling Trousers": "Dazzling Trousers",
  "Dazzling Slippers": "Dazzling Slippers",
  "Resplendent Crown": "Resplendent Crown",
  "Resplendent Robe": "Resplendent Robe",
  "Resplendent Sleeves": "Resplendent Sleeves",
  "Resplendent Wristguard": "Resplendent Wristguard",
  "Resplendent Gloves": "Resplendent Gloves",
  "Resplendent Trousers": "Resplendent Trousers",
  "Resplendent Slippers": "Resplendent Slippers"
}

const magician = {
    "Apothic Crown": "Apothic Crown",
    "Apothic Boots": "Apothic Boots",
    "Apothic Gloves": "Apothic Gloves",
    "Apothic Kilt": "Apothic Kilt",
    "Apothic Robe": "Apothic Robe",
    "Apothic Sleeves": "Apothic Sleeves",
    "Apothic Wristguard": "Apothic Wristguard",
    "Prestidigitator's Headband": "Prestidigitator's Headband",
  "Prestidigitator's Robe": "Prestidigitator's Robe",
  "Prestidigitator's Sleeves": "Prestidigitator's Sleeves",
  "Prestidigitator's Wristband": "Prestidigitator's Wristband",
  "Prestidigitator's Gloves": "Prestidigitator's Gloves",
  "Prestidigitator's Trousers": "Prestidigitator's Trousers",
  "Prestidigitator's Boots": "Prestidigitator's Boots",
  "Summoner's Circlet": "Summoner's Circlet",
  "Summoner's Robe": "Summoner's Robe",
  "Summoner's Sleeves": "Summoner's Sleeves",
  "Summoner's Warband": "Summoner's Warband",
  "Summoner's Gloves": "Summoner's Gloves",
  "Summoner's Pantaloons": "Summoner's Pantaloons",
  "Summoner's Boots": "Summoner's Boots",
  "Arch Mage's Crown": "Arch Mage's Crown",
  "Arch Mage's Robe": "Arch Mage's Robe",
  "Arch Mage's Sleeves": "Arch Mage's Sleeves",
  "Arch Mage's Warband": "Arch Mage's Warband",
  "Arch Mage's Gloves": "Arch Mage's Gloves",
  "Arch Mage's Pantaloons": "Arch Mage's Pantaloons",
  "Arch Mage's Boots": "Arch Mage's Boots",
  "Circlet of Conjuration": "Circlet of Conjuration",
  "Robe of Conjuration": "Robe of Conjuration",
  "Sleeves of Conjuration": "Sleeves of Conjuration",
  "Wristband of Conjuration": "Wristband of Conjuration",
  "Gloves of Conjuration": "Gloves of Conjuration",
  "Pantaloons of Conjuration": "Pantaloons of Conjuration",
  "Boots of Conjuration": "Boots of Conjuration"
};

const wizard = {
    "Carmine Boots": "Carmine Boots",
  "Carmine Gloves": "Carmine Gloves",
  "Carmine Pants": "Carmine Pants",
  "Carmine Robe": "Carmine Robe",
  "Carmine Sleeves": "Carmine Sleeves",
  "Carmine Trinket": "Carmine Trinket",
  "Carmine Turban": "Carmine Turban",
  "Robe of Icicles": "Robe of Icicles",
  "Icicle Circlet": "Icicle Circlet",
  "Icicle Sleeves": "Icicle Sleeves",
  "Icicle Bracelet": "Icicle Bracelet",
  "Icicle Gloves": "Icicle Gloves",
  "Icicle Pantaloons": "Icicle Pantaloons",
  "Icicle Boots": "Icicle Boots",
  "Invoker's Circlet": "Invoker's Circlet",
  "Invoker's Robe": "Invoker's Robe",
  "Invoker's Sleeves": "Invoker's Sleeves",
  "Invoker's Bangle": "Invoker's Bangle",
  "Invoker's Gloves": "Invoker's Gloves",
  "Invoker's Pants": "Invoker's Pants",
  "Invoker's Boots": "Invoker's Boots",
  "Sage's Crown": "Sage's Crown",
  "Sage's Robe": "Sage's Robe",
  "Sage's Sleeves": "Sage's Sleeves",
  "Sage's Bracelet": "Sage's Bracelet",
  "Sage's Gloves": "Sage's Gloves",
  "Sage's Pantaloons": "Sage's Pantaloons",
  "Sage's Boots": "Sage's Boots",
  "Sorcerer's Circlet": "Sorcerer's Circlet",
  "Sorcerer's Robe": "Sorcerer's Robe",
  "Sorcerer's Sleeves": "Sorcerer's Sleeves",
  "Sorcerer's Wristband": "Sorcerer's Wristband",
  "Sorcerer's Gloves": "Sorcerer's Gloves",
  "Sorcerer's Pantaloons": "Sorcerer's Pantaloons",
  "Sorcerer's Boots": "Sorcerer's Boots"
}

const necromancer = {
    "Blighted Armband": "Blighted Armband",
  "Blighted Boots": "Blighted Boots",
  "Blighted Gloves": "Blighted Gloves",
  "Blighted Robe": "Blighted Robe",
  "Blighted Skullcap": "Blighted Skullcap",
  "Blighted Sleeves": "Blighted Sleeves",
  "Blighted Trousers": "Blighted Trousers",
  "Rotting Crown": "Rotting Crown",
  "Rotting Robe": "Rotting Robe",
  "Rotting Sleeves": "Rotting Sleeves",
  "Rotting Wristguard": "Rotting Wristguard",
  "Rotting Gloves": "Rotting Gloves",
  "Rotting Trousers": "Rotting Trousers",
  "Rotting Boots": "Rotting Boots",
  "Plague Bearer's Circlet": "Plague Bearer's Circlet",
  "Plague Bearer's Robe": "Plague Bearer's Robe",
  "Plague Bearer's Sleeves": "Plague Bearer's Sleeves",
  "Plague Bearer's Wristguard": "Plague Bearer's Wristguard",
  "Plague Bearer's Gloves": "Plague Bearer's Gloves",
  "Plague Bearer's Trousers": "Plague Bearer's Trousers",
  "Plague Bearer's Boots": "Plague Bearer's Boots",
  "Warlock's Crown": "Warlock's Crown",
  "Warlock's Robe": "Warlock's Robe",
  "Warlock's Sleeves": "Warlock's Sleeves",
  "Warlock's Wristguard": "Warlock's Wristguard",
  "Warlock's Gloves": "Warlock's Gloves",
  "Warlock's Pantaloons": "Warlock's Pantaloons",
  "Warlock's Boots": "Warlock's Boots",
  "Crown of the Bonecaster": "Crown of the Bonecaster",
  "Robe of the Bonecaster": "Robe of the Bonecaster",
  "Sleeves of the Bonecaster": "Sleeves of the Bonecaster",
  "Wristband of the Bonecaster": "Wristband of the Bonecaster",
  "Gloves of the Bonecaster": "Gloves of the Bonecaster",
  "Pantaloons of the Bonecaster": "Pantaloons of the Bonecaster",
  "Boots of the Bonecaster": "Boots of the Bonecaster",
}

const rogue = {
    "Woven Shadow Boots": "Woven Shadow Boots",
  "Woven Shadow Bracer": "Woven Shadow Bracer",
  "Woven Shadow Chestplate": "Woven Shadow Chestplate",
  "Woven Shadow Gauntlets": "Woven Shadow Gauntlets",
  "Woven Shadow Greaves": "Woven Shadow Greaves",
  "Woven Shadow Helm": "Woven Shadow Helm",
  "Woven Shadow Vambraces": "Woven Shadow Vambraces",
  "Shadow Crown": "Shadow Crown",
  "Shadow Chestguard": "Shadow Chestguard",
  "Shadow Vambraces": "Shadow Vambraces",
  "Shadow Bracer": "Shadow Bracer",
  "Shadow Gauntlets": "Shadow Gauntlets",
  "Shadow Greaves": "Shadow Greaves",
  "Shadow Boots": "Shadow Boots",
  "Deceiver's Crown": "Deceiver's Crown",
  "Deceiver's Chestguard": "Deceiver's Chestguard",
  "Deceiver's Vambraces": "Deceiver's Vambraces",
  "Deceiver's Bracer": "Deceiver's Bracer",
  "Deceiver's Gauntlets": "Deceiver's Gauntlets",
  "Deceiver's Greaves": "Deceiver's Greaves",
  "Deceiver's Boots": "Deceiver's Boots",
  "Brigand's Circlet": "Brigand's Circlet",
  "Brigand's Chestguard": "Brigand's Chestguard",
  "Brigand's Vambraces": "Brigand's Vambraces",
  "Brigand's Bracer": "Brigand's Bracer",
  "Brigand's Gauntlets": "Brigand's Gauntlets",
  "Brigand's Greaves": "Brigand's Greaves",
  "Brigand's Boots": "Brigand's Boots",
  "Assassin's Coif":"Assassin's Coif",
"Assassin's Chestguard":"Assassin's Chestguard",
"Assassin's Chain Sleeves":"Assassin's Chain Sleeves",
"Assassin's Bracer":"Assassin's Bracer",
"Assassin's Gauntlets":"Assassin's Gauntlets",
"Assassin's Chain Leggings":"Assassin's Chain Leggings",
"Assassin's Boots":"Assassin's Boots",
}

const warrior = {
    "Indicolite Boots": "Indicolite Boots",
    "Indicolite Helm": "Indicolite Helm",
    "Indicolite Breastplate": "Indicolite Breastplate",
    "Indicolite Vambraces": "Indicolite Vambraces",
    "Indicolite Bracer": "Indicolite Bracer",
    "Indicolite Gauntlets": "Indicolite Gauntlets",
    "Indicolite Greaves": "Indicolite Greaves",
    "Legionnaire Scale Boots": "Legionnaire Scale Boots",
  "Legionnaire Scale Helm": "Legionnaire Scale Helm",
  "Legionnaire Scale Breastplate": "Legionnaire Scale Breastplate",
  "Legionnaire Scale Pauldron": "Legionnaire Scale Pauldron",
  "Legionnaire Scale Vambraces": "Legionnaire Scale Vambraces",
  "Legionnaire Scale Bracers": "Legionnaire Scale Bracers",
  "Legionnaire Scale Gauntlets": "Legionnaire Scale Gauntlets",
  "Legionnaire Scale Greaves": "Legionnaire Scale Greaves",
  "Crown of the Myrmidon": "Crown of the Myrmidon",
  "Breastplate of the Myrmidon": "Breastplate of the Myrmidon",
  "Vambraces of the Myrmidon": "Vambraces of the Myrmidon",
  "Bracer of the Myrmidon": "Bracer of the Myrmidon",
  "Gauntlets of the Myrmidon": "Gauntlets of the Myrmidon",
  "Greaves of the Myrmidon": "Greaves of the Myrmidon",
  "Boots of the Myrmidon": "Boots of the Myrmidon",
  "Warlord's Crown": "Warlord's Crown",
  "Warlord's Breastplate": "Warlord's Breastplate",
  "Warlord's Vambraces": "Warlord's Vambraces",
  "Warlord's Bracer": "Warlord's Bracer",
  "Warlord's Gauntlets": "Warlord's Gauntlets",
  "Warlord's Greaves": "Warlord's Greaves",
  "Warlord's Boots": "Warlord's Boots",
  "Champion's Crown": "Champion's Crown",
  "Champion's Breastplate": "Champion's Breastplate",
  "Champion's Vambraces": "Champion's Vambraces",
  "Champion's Bracer": "Champion's Bracer",
  "Champion's Gauntlets": "Champion's Gauntlets",
  "Champion's Greaves": "Champion's Greaves",
  "Champion's Boots": "Champion's Boots",
  "Berserker's Helm": "Berserker's Helm",
  "Berserker's Breastplate": "Berserker's Breastplate",
  "Berserker's Vambraces": "Berserker's Vambraces",
  "Berserker's Bracer": "Berserker's Bracer",
  "Berserker's Gauntlets": "Berserker's Gauntlets",
  "Berserker's Greaves": "Berserker's Greaves",
  "Berserker's Boots": "Berserker's Boots"
}

const monk = {
    "Shiverback-hide Armbands": "Shiverback-hide Armbands",
    "Shiverback-hide Boots": "Shiverback-hide Boots",
    "Shiverback-hide Gloves": "Shiverback-hide Gloves",
    "Shiverback-hide Jerkin": "Shiverback-hide Jerkin",
    "Shiverback-hide Leggings": "Shiverback-hide Leggings",
    "Shiverback-hide Wristbands": "Shiverback-hide Wristbands",
    "White Lotus Headband": "White Lotus Headband",
  "White Lotus Chest Wraps": "White Lotus Chest Wraps",
  "White Lotus Arm Wraps": "White Lotus Arm Wraps",
  "White Lotus Wrist Wraps": "White Lotus Wrist Wraps",
  "White Lotus Pants": "White Lotus Pants",
  "White Lotus Slippers": "White Lotus Slippers",
  "Golden Star Headband": "Golden Star Headband",
  "Golden Star Chest Wraps": "Golden Star Chest Wraps",
  "Golden Star Arm Wraps": "Golden Star Arm Wraps",
  "Golden Star Wrist Wraps": "Golden Star Wrist Wraps",
  "Golden Star Pants": "Golden Star Pants",
  "Golden Star Slippers": "Golden Star Slippers",
  "Grand Master's Headband": "Grand Master's Headband",
  "Grand Master's Chest Wraps": "Grand Master's Chest Wraps",
  "Grand Master's Arm Wraps": "Grand Master's Arm Wraps",
  "Grand Master's Wrist Wraps": "Grand Master's Wrist Wraps",
  "Grand Master's Leg Wraps": "Grand Master's Leg Wraps",
  "Grand Master's Slippers": "Grand Master's Slippers",
  "Silver Moon Headband": "Silver Moon Headband",
  "Silver Moon Chest Wraps": "Silver Moon Chest Wraps",
  "Silver Moon Arm Wraps": "Silver Moon Arm Wraps",
  "Silver Moon Wrist Wraps": "Silver Moon Wrist Wraps",
  "Silver Moon Pants": "Silver Moon Pants",
  "Silver Moon Slippers": "Silver Moon Slippers",
};

const shadowknight = {
    "Umbral Platemail Boots": "Umbral Platemail Boots",
  "Umbral Platemail Bracer": "Umbral Platemail Bracer",
  "Umbral Platemail Breastplate": "Umbral Platemail Breastplate",
  "Umbral Platemail Gauntlets": "Umbral Platemail Gauntlets",
  "Umbral Platemail Greaves": "Umbral Platemail Greaves",
  "Umbral Platemail Helm": "Umbral Platemail Helm",
  "Umbral Platemail Vambraces": "Umbral Platemail Vambraces",
  "Greenmist Mask": "Greenmist Mask",
  "Greenmist Boots": "Greenmist Boots",
  "Greenmist Greaves": "Greenmist Greaves",
  "Greenmist Bracer": "Greenmist Bracer",
  "Greenmist Vambraces": "Greenmist Vambraces",
  "Greenmist Breastplate": "Greenmist Breastplate",
  "Greenmist Helm": "Greenmist Helm",
  "Blood Lord's Crown": "Blood Lord's Crown",
  "Blood Lord's Breastplate": "Blood Lord's Breastplate",
  "Blood Lord's Vambraces": "Blood Lord's Vambraces",
  "Blood Lord's Bracer": "Blood Lord's Bracer",
  "Blood Lord's Gauntlets": "Blood Lord's Gauntlets",
  "Blood Lord's Greaves": "Blood Lord's Greaves",
  "Blood Lord's Boots": "Blood Lord's Boots",
  "Malevolent Crown": "Malevolent Crown",
  "Malevolent Breastplate": "Malevolent Breastplate",
  "Malevolent Vambraces": "Malevolent Vambraces",
  "Malevolent Bracer": "Malevolent Bracer",
  "Malevolent Gauntlets": "Malevolent Gauntlets",
  "Malevolent Greaves": "Malevolent Greaves",
  "Malevolent Boots": "Malevolent Boots",
  "Dark Runed Crown": "Dark Runed Crown",
  "Dark Runed Breastplate": "Dark Runed Breastplate",
  "Dark Runed Vambraces": "Dark Runed Vambraces",
  "Dark Runed Bracer": "Dark Runed Bracer",
  "Dark Runed Gauntlets": "Dark Runed Gauntlets",
  "Dark Runed Greaves": "Dark Runed Greaves",
  "Dark Runed Boots": "Dark Runed Boots",
  "Noctivigant Crown": "Noctivigant Crown",
  "Noctivigant Breastplate": "Noctivigant Breastplate",
  "Noctivigant Vambraces": "Noctivigant Vambraces",
  "Noctivigant Bracer": "Noctivigant Bracer",
  "Noctivigant Gauntlets": "Noctivigant Gauntlets",
  "Noctivigant Greaves": "Noctivigant Greaves",
  "Noctivigant Boots": "Noctivigant Boots"
}

const paladin = {
"Vermiculated Boots":"Vermiculated Boots",
"Vermiculated Bracelet":"Vermiculated Bracelet",
"Vermiculated Crown":"Vermiculated Crown",
"Vermiculated Gloves":"Vermiculated Gloves",
"Vermiculated Leggings":"Vermiculated Leggings",
"Vermiculated Armplates":"Vermiculated Armplates",
"Vermiculated Tunic":"Vermiculated Tunic",
"Scaled Knight's Helm":"Scaled Knight's Helm",
"Scaled Knight's Breastplate":"Scaled Knight's Breastplate",
"Scaled Knight's Vambraces":"Scaled Knight's Vambraces",
"Scaled Knight's Bracer":"Scaled Knight's Bracer",
"Scaled Knight's Gauntlets":"Scaled Knight's Gauntlets",
"Scaled Knight's Greaves":"Scaled Knight's Greaves",
"Scaled Knight's Boots":"Scaled Knight's Boots",
"Shining Helm":"Shining Helm",
"Shining Breastplate":"Shining Breastplate",
"Shining Vambraces":"Shining Vambraces",
"Shining Bracer":"Shining Bracer",
"Shining Gauntlets":"Shining Gauntlets",
"Shining Greaves":"Shining Greaves",
"Shining Boots":"Shining Boots",
"Runed Protector's Helm":"Runed Protector's Helm",
"Runed Protector's Breastplate":"Runed Protector's Breastplate",
"Runed Protector's Vambraces":"Runed Protector's Vambraces",
"Runed Protector's Bracer":"Runed Protector's Bracer",
"Runed Protector's Gauntlets":"Runed Protector's Gauntlets",
"Runed Protector's Greaves":"Runed Protector's Greaves",
"Runed Protector's Boots":"Runed Protector's Boots",
"Helm of the Righteous":"Helm of the Righteous",
"Breastplate of the Righteous":"Breastplate of the Righteous",
"Vambraces of the Righteous":"Vambraces of the Righteous",
"Bracer of the Righteous":"Bracer of the Righteous",
"Gauntlets of the Righteous":"Gauntlets of the Righteous",
"Greaves of the Righteous":"Greaves of the Righteous",
"Boots of the Righteous":"Boots of the Righteous",
}

const shaman = {
"Wolf Caller's Helm":"Wolf Caller's Helm",
"Wolf Caller's Breastplate":"Wolf Caller's Breastplate",
"Wolf Caller's Vambraces":"Wolf Caller's Vambraces",
"Wolf Caller's Bracer":"Wolf Caller's Bracer",
"Wolf Caller's Gauntlets":"Wolf Caller's Gauntlets",
"Wolf Caller's Greaves":"Wolf Caller's Greaves",
"Wolf Caller's Boots":"Wolf Caller's Boots",
"Spirit Caller's Helm":"Spirit Caller's Helm",
"Spirit Caller's Breastplate":"Spirit Caller's Breastplate",
"Spirit Caller's Vambraces":"Spirit Caller's Vambraces",
"Spirit Caller's Bracer":"Spirit Caller's Bracer",
"Spirit Caller's Gauntlets":"Spirit Caller's Gauntlets",
"Spirit Caller's Greaves":"Spirit Caller's Greaves",
"Spirit Caller's Boots":"Spirit Caller's Boots",
"Rune Etched Boots":"Rune Etched Boots",
"Rune Etched Bracer":"Rune Etched Bracer",
"Rune Etched Chestplate":"Rune Etched Chestplate",
"Rune Etched Gauntlets":"Rune Etched Gauntlets",
"Rune Etched Greaves":"Rune Etched Greaves",
"Rune Etched Helm":"Rune Etched Helm",
"Rune Etched Vambraces":"Rune Etched Vambraces",
"Scaled Hierophant Cloak":"Scaled Hierophant Cloak",
"Scaled Hierophant Helm":"Scaled Hierophant Helm",
"Scaled Hierophant Breastplate":"Scaled Hierophant Breastplate",
"Scaled Hierophant Bracers":"Scaled Hierophant Bracers",
"Scaled Hierophant Greaves":"Scaled Hierophant Greaves",
"Scaled Hierophant Vambraces":"Scaled Hierophant Vambraces",
"Scaled Hierophant Gauntlets":"Scaled Hierophant Gauntlets",
"Scaled Hierophant Boots":"Scaled Hierophant Boots",
"Rune Crafter's Helm":"Rune Crafter's Helm",
"Rune Crafter's Breastplate":"Rune Crafter's Breastplate",
"Rune Crafter's Vambraces":"Rune Crafter's Vambraces",
"Rune Crafter's Bracer":"Rune Crafter's Bracer",
"Rune Crafter's Gauntlets":"Rune Crafter's Gauntlets",
"Rune Crafter's Greaves":"Rune Crafter's Greaves",
"Rune Crafter's Boots":"Rune Crafter's Boots",
"Spirit Weaver's Coif":"Spirit Weaver's Coif",
"Spirit Weaver's Breastplate":"Spirit Weaver's Breastplate",
"Spirit Weaver's Vambraces":"Spirit Weaver's Vambraces",
"Spirit Weaver's Bracer":"Spirit Weaver's Bracer",
"Spirit Weaver's Gauntlets":"Spirit Weaver's Gauntlets",
"Spirit Weaver's Greaves":"Spirit Weaver's Greaves",
"Spirit Weaver's Boots":"Spirit Weaver's Boots",
}

const ranger = {
"Thorny Vine Boots":"Thorny Vine Boots",
"Thorny Vine Bracer":"Thorny Vine Bracer",
"Thorny Vine Chestplate":"Thorny Vine Chestplate",
"Thorny Vine Gauntlets":"Thorny Vine Gauntlets",
"Thorny Vine Greaves":"Thorny Vine Greaves",
"Thorny Vine Helm":"Thorny Vine Helm",
"Thorny Vine Vambraces":"Thorny Vine Vambraces",
"Helm of the Untamed":"Helm of the Untamed",
"Breastplate of the Untamed":"Breastplate of the Untamed",
"Vambraces of the Untamed":"Vambraces of the Untamed",
"Bracer of the Untamed":"Bracer of the Untamed",
"Gauntlets of the Untamed":"Gauntlets of the Untamed",
"Greaves of the Untamed":"Greaves of the Untamed",
"Boots of the Untamed":"Boots of the Untamed",
"Helm of the Righteous":"Helm of the Righteous",
"Breastplate of the Righteous":"Breastplate of the Righteous",
"Vambraces of the Righteous":"Vambraces of the Righteous",
"Bracer of the Righteous":"Bracer of the Righteous",
"Gauntlets of the Righteous":"Gauntlets of the Righteous",
"Greaves of the Righteous":"Greaves of the Righteous",
"Boots of the Righteous":"Boots of the Righteous",
"Scaled Knight's Helm":"Scaled Knight's Helm",
"Scaled Knight's Breastplate":"Scaled Knight's Breastplate",
"Scaled Knight's Vambraces":"Scaled Knight's Vambraces",
"Scaled Knight's Bracer":"Scaled Knight's Bracer",
"Scaled Knight's Gauntlets":"Scaled Knight's Gauntlets",
"Scaled Knight's Greaves":"Scaled Knight's Greaves",
"Scaled Knight's Boots":"Scaled Knight's Boots",
"Shining Helm":"Shining Helm",
"Shining Breastplate":"Shining Breastplate",
"Shining Vambraces":"Shining Vambraces",
"Shining Bracer":"Shining Bracer",
"Shining Gauntlets":"Shining Gauntlets",
"Shining Greaves":"Shining Greaves",
"Shining Boots":"Shining Boots",
}

export const classArmor = {
  Bard: bard, 
  Cleric: cleric, 
  Druid: druid, 
  Enchanter: enchanter, 
  Magician: magician, 
  Wizard: wizard, 
  Necromancer: necromancer, 
  Rogue: rogue, 
  Warrior: warrior, 
  Monk: monk, 
  Shadowknight: shadowknight,
  Paladin: paladin,
  Shaman: shaman,
  Ranger: ranger,
};